
hdf5_root: "/mnt/disk1/m3ed"
save_root: "/mnt/disk1/m3ed"

# Files to be processed
files:
  - file_name: "car_urban_day_city_hall_data.h5"
    save_name: "car_urban_day_city_hall_1.h5"
    start_time: 0026
    end_time: 0030

  # - file_name: "car_urban_day_city_hall_data.h5"
  #   save_name: "car_urban_day_city_hall_2"
  #   start_time: 0031
  #   end_time: 0035
